# Generated by Django 5.0.6 on 2024-06-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, default='assembling', max_length=255, null=True, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
