# Generated by Django 5.0.6 on 2024-06-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categorical'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('archived', 'archived')], default='open', max_length=255),
        ),
    ]
