# Generated by Django 5.0.6 on 2024-06-17 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_delivery_address_alter_order_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Примечание')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.reservproduct', verbose_name='Ссылка на купленныйф продукт'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
