# Generated by Django 5.0.6 on 2024-06-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_status'),
        ('shop', '0010_alter_reservproduct_product'),
    ]

    operations = [
    ]
