# Generated by Django 5.0.6 on 2024-06-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_reservproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наменование'),
        ),
    ]
