# Generated by Django 5.0.6 on 2024-06-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_education_name'),
        ('shop', '0014_subuser_phone'),
    ]

    operations = [
    ]
