# Generated by Django 5.0.6 on 2024-06-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_merge_0011_alter_education_name_0014_subuser_phone'),
        ('shop', '0016_alter_order_status'),
    ]

    operations = [
    ]
