# Generated by Django 5.0.6 on 2024-05-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RS485', models.BooleanField(blank=True, default=False)),
                ('Wi_Fi', models.BooleanField(blank=True, default=False)),
                ('TWI', models.BooleanField(blank=True, default=False)),
                ('buttons', models.BooleanField(blank=True, default=False)),
                ('sensors', models.BooleanField(blank=True, default=False)),
                ('panels_management', models.BooleanField(blank=True, default=False)),
                ('controllers_management', models.BooleanField(blank=True, default=False)),
                ('relay', models.BooleanField(blank=True, default=False)),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
