# Generated by Django 5.0.6 on 2024-06-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_products_reservproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.delivery_address', verbose_name='Адрес Доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.TextField(blank=True, default='SBP', null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='reservproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Количество'),
        ),
    ]
