# Generated by Django 5.0.6 on 2024-06-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_reservproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', unique=True, verbose_name='Продукт'),
        ),
    ]
