# Generated by Django 5.0.6 on 2024-06-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_education_name_contetnlearn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='deliveryAddress',
        ),
    ]
