# Generated by Django 5.0.6 on 2024-06-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_delivery_address_order_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='phone',
            field=models.CharField(default='+7(000)000-00-00', max_length=20, null=True),
        ),
    ]
