# Generated by Django 5.0.6 on 2024-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('archived', 'archived')], default='open', max_length=255),
        ),
    ]
